// Fifty distinct conversational situations, including natural paraphrases missed by the old matcher.
export const coachCases=[
 ['No termino de ver qué ganamos en casa','value',/mejorar|prestación|necesidad/, 'Mi pareja dice que primero lo hablemos en casa','family',/juntos|familia|resumen/],
 ['¿Y si cuando vaya al hospital me dicen que no?','authorization',/autorización|negativa|centro/, 'Me preocupa que me pongan pegas al autorizar una prueba','authorization',/procedimiento|autorización/],
 ['Me da reparo meterme en otro recibo fijo','budget',/pago fijo|coste|límite/, 'No puedo asumir muchos gastos más','budget',/mantener|alternativa/],
 ['Necesito hablarlo con mis hijos antes de decidir','family',/familia|juntos|resumen/, 'No decido yo sola','family',/juntos|todos/],
 ['En la última póliza me marearon para autorizar una prueba','authorization',/procedimiento|autorización/, 'Ya me denegaron una prueba antes','authorization',/atención|condiciones/],
 ['Lo que me preocupa es quedarme tirado cuando haga falta','authorization',/negativa|condiciones/, 'No quiero que me dejen tirado en el hospital','authorization',/centro|atención/],
 ['Es que no quiero otro compromiso ahora','timing',/compromiso|decisión/, 'Ahora no es el momento','timing',/momento|revisarlo/],
 ['¿Y si mi hijo necesita atención antes de que empiece la póliza?','effective',/fecha de efecto|carencias/, '¿Desde qué fecha puedo utilizarlo?','effective',/fecha|aceptación/],
 ['Eso cuesta un dineral','price',/coste|importe/, 'En otro sitio sale más barato','compare',/comparar|propuestas/],
 ['Son muchos euros para lo que gano','price',/importe|coste/, 'No me llega el sueldo para otro gasto','budget',/mantener|pago/],
 ['¿Tendré que pagar otra vez cuando vaya?','copago',/copagos/, 'No quiero pagar cada visita','copago',/copagos|coste completo/],
 ['No quiero sorpresas en los recibos','copago',/copagos|cuota/, '¿Cuánto pagaré al ir al especialista?','copago',/copagos|servicios/],
 ['Me siento atada con tres años','duration',/duración|baja/, 'Quiero salirme cuando quiera','duration',/cancelar|baja/],
 ['Si me quedo sin trabajo, ¿seguiré pagando?','duration',/duración|renovación/, 'Pagar al mes no es lo mismo que poder salir cada mes, ¿verdad?','duration',/meses|cancelar/],
 ['Todo suena demasiado bonito','trust',/documentación|verifica/, 'Quiero ver la letra pequeña','trust',/límites|carencias/],
 ['¿Dónde está la trampa?','trust',/documentación|condiciones/, 'No me creo lo que dices hasta verlo escrito','trust',/documentación|oficial/],
 ['¿A dónde van mis datos?','trust',/canal|identidad|documentación/, 'Te doy mi IBAN para avanzar','privacy',/canal|datos/],
 ['Ni he abierto la propuesta','review',/repasar|esencial/, 'No tuve un momento para mirarla','review',/momento|minutos/],
 ['Se me olvidó revisar el correo','review',/repasar|esencial/, 'Ahora sí tengo dos minutos para repasar','short',/pendiente|retomemos/],
 ['Estoy en Sanitas y no quiero perder lo que tengo','current',/continuidad|perder|cambiar/, 'Me preocupa la cobertura duplicada','current',/comparamos|comparemos/],
 ['Ya estoy en Asisa','current',/seguro actual|cambiar|tienes/, '¿Qué diferencia hay con mi póliza?','current',/prestaciones|carencias/],
 ['El banco me da otro presupuesto','compare',/propuestas|criterios/, 'Quiero comparar los dos con el mismo hospital','compare',/centros|prestaciones/],
 ['Quiero confirmar que puedo seguir con mi cardiólogo','doctor',/profesional|cuadro|médico/, '¿Y la clínica de mi barrio?','doctor',/cuadro|centro/],
 ['Necesito un centro cerca de mi barrio','doctor',/centro|localidad/, '¿Puedo continuar con el mismo especialista?','doctor',/especialista|profesional|cuadro/],
 ['Me operaron hace dos años, ¿me aceptaréis?','medical',/cuestionario|valoración/, 'Tomo metformina a diario','medical',/valoración|exactitud/],
 ['¿Me excluirán por ese diagnóstico?','medical',/valoración|exclusiones/, 'No pongas la enfermedad para que salga mejor','exactitud',/exactitud|salud/],
 ['¿Desde el primer día me puedo hacer una resonancia?','carencia',/carencia|fecha/, 'Quiero contratar, pero solo si me sirve para la prueba de mañana','conditional',/comprobar|condición/],
 ['Llevo meses en lista de espera','carencia',/carencia|fecha/, 'Necesito una operación este mes','carencia',/prestación|compañía/],
 ['¿Me lo mandas antes de decidir?','written',/documentación|canal/, 'No tengo tu mensaje','written',/envío|canal|documentación/],
 ['Pásame las condiciones completas','written',/documentación|condiciones/, 'No recibí el correo','delivery',/envío|llegado/],
 ['No quiero contratar todavía','pending',/decidir|todavía|aún/, 'Prefiero evaluarlo con calma','pensar',/evaluar|valorar|pensar|decidir/],
 ['Prefiero no seguir','decline',/propuesta|aquí|tiempo/, 'No vuelvas a molestarme','stop',/llamar|contact/],
 ['He decidido que no','decline',/propuesta|aquí|tiempo/, 'No quiero que me contactes','stop',/llamar|contact/],
 ['No me presiones, necesito tiempo','pressure',/perdona|tiempo|decisión/, 'Deja de insistir','pressure',/perdona|decisión/],
 ['Sácame de tu lista','stop',/llamar|contact/, 'Aunque cambie el precio, no quiero otra llamada','stop',/llamar|contact/],
 ['Ya tengo la pública','publica',/pública|necesidad|complemento/, 'No veo qué ventaja tendría','value',/necesidad|prestación/],
 ['Nunca voy al médico','uso',/uso|necesidad|salud/, 'No veo el sentido de pagar por esto','value',/necesidad|coste|prestación/],
 ['Me preocupa la subida en renovación','subidas',/renovación|prima|subida/, '¿Me garantizas que jamás subirá?','guarantee',/garant|comprobar/],
 ['No quiero copagos','copago',/cada uso|copagos/, 'No es caro, es que quiero cero copagos','copago',/copagos|cada uso/],
 ['Quiero hablarlo con mi marido','pareja',/juntos|decid/, 'Mis padres también quieren verlo','family',/familia|resumen|todos/],
 ['¿Es mensual el pago?','payment',/cobra|pago/, '¿Puedo darme de baja cuando quiera?','duration',/baja|cancelar/],
 ['Vi otro precio en el anuncio','anuncio',/anunciado|precio/, 'Parece que me vendes humo','trust',/documentación|verifica/],
 ['¿Cubre implantes?','dental',/dental|tratamiento/, 'No quiero pagar cada visita al dentista','copago',/copagos|coste/],
 ['¿Mi medicación genera rechazo?','patologia',/valoración|valorarse|compañía|aseguradora|confirm/, '¿Y si ocultamos el diagnóstico?','exactitud',/exactitud|salud/],
 ['¿Cubre hospitalización?','coberturas',/prestación|modalidad|comprobar/, 'Quiero contratar, pero solo si cubre mi hospital','conditional',/condición|comprobar/],
 ['No entiendo lo que incluye','coberturas',/comprobar|prestación/, '¿Qué me aporta en la práctica?','value',/necesidad|prestación/],
 ['Tengo un seguro de viaje, ¿para qué cambiar?','viaje',/destino|viaje/, 'Necesito comparar otra oferta','compare',/propuestas|criterios/],
 ['Tengo un perro y busco algo para el veterinario','mascotas',/mascota|veterinar/, '¿Puedo seguir con mi veterinario?','doctor',/profesional|centro|cuadro/],
 ['Quiero contratar si el precio final es ese','conditional',/precio|condición/, 'Aún quiero revisar la duración antes','duracion',/duración|compromiso/],
 ['Adelante, iniciemos la solicitud','ready',/solicitud|aceptación|modalidad/, 'Pero no estoy seguro de las carencias','carencias',/carencia|prestación|plazo/]
];
